apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-foo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: counter
  destination:
    namespace: counter-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/ondrejsika/counter.git
    path: charts/counter
    helm:
      valueFiles:
      - $values/values.yaml
      - $values/values-dev.yaml
  - repoURL: 'https://gitlab.sikademo.com/training/counter-foo.git'
    targetRevision: main
    ref: values
