apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: sikalabs/hello-world-server
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: "TEXT"
              value: "Hello ArgoCD!"
            - name: "COLOR"
              value: '#DBE0DF'
            - name: "BACKGROUND_COLOR"
              value: '#0F2833'
